apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREF4TVRneQpNekV3TXpWYUZ3MDBNREF4TVRneU16RXdNelZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEajBiSGFHaGZDU2EwQmdLTXA2cEI3RVBiWTBpamsycHNGMUh0aS9uRE81THhrUjhJUwpnZnRML1pKUzkrNi9pVExpNmZOSExFN1ZPMEQrZWhnY20yNXV1dDdsTFVRVit0TnphTEgrUGpmSFZnMGVIaWNZClNVL1o3QVJwenJjY2VCYzVaVDgrdk54Q0tEYVo0VC9HRlpibU96N0JOUHRGTHNlR1BLVGFIRTVjUFRqY1FKR0oKRVZzZ0F3R0FnbTBucFJ2T215NUhqK3dHb3VzQkxHTXdYencxLytKZXNlQ3RGTnUybXhoSjk0TzRLbnV3Sll5OAptM0dlNUE2ZUNZYnArNTV5Q1VUUEs2dU5Ud1RpR3BNK0VXQ2xHNnUzdlZrYlpQZ09sMmZ0SDJWb2R5S1Q5dFY5CjlLMFRKalFDQ2hSQjJjK2xSM1pFZ3pweHlpSEsxYUxYcHJtekFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFTcGlBWXkrUUNuYUsxcjBaOQptYzYvbEwwenREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEzWUJyUzVRMUxqZjdZNTZCQ0JYZW5pdG0zb0U2Clpnc09xbTlwMjBFK2g1MVNxWExQTDBVL3R2MkFjREh6amhQbk5xbkwrMkcxZGRPZXNZR1lsbW1sWEJaTDE5QnkKNUxnMXZjbmpadUE5c1BBZDE3RUpXZTVpQUJwQU5RcXVLWEpKcE91TS8zUFdvR2VaT3M2OHJBOGZSdnI4cGFXZgpVOXd6WVhaWXNTNHBYU1FqcEhPNlpUVGQzcVgxQkVCTHdYLytCTWZ1MXE3Sno2a0ovNnRaZXc2ZWoyWElGTW9tCmlXeTJzaTdvSzlVUTcrU2h4MHBsZXJIMjJlVDVZWHFPZmJXaUIwQ0tZbmM1TGNjQkJ0Q1c0YjgzbGoxMkt0LzkKcUNXVlZ5eVFqU1VXQVZKSTV0dy92aFE4RVFtaThlRi9nWFVSalpWdlQ4WlVHbE5sRzBaQXlBenN0QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0bb5ecc7-53af-4124-94f5-6e41fed62141.k8s.ondigitalocean.com
  name: do-lon1-foo
contexts:
- context:
    cluster: do-lon1-foo
    user: do-lon1-foo-admin
  name: do-lon1-foo
current-context: do-lon1-foo
kind: Config
preferences: {}
users:
- name: do-lon1-foo-admin
  user:
    token: fd3b3fea74f6c74b30b21daa5e4099b7a044e99601e3a643fb4c1564ba31bfba
