version: '3'
services:
  monster_icon:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CONTEXT=DEV
    volumes:
      - ./app:/app
    networks:
      - monster_network

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - monster_network

  redis:
    image: redis
    networks:
      - monster_network

networks:
  monster_network:
    driver: bridge
