version: '3'
services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CONTEXT=DEV
    volumes:
      - ./app:/app
    networks:
      - identinet

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - identinet

  redis:
    image: redis
    networks:
      - identinet

networks:
  identinet:
    driver: bridge
