- hosts: docker_swarm_manager
  become: yes

  tasks:

    - name: copy portainer app stack file to remote
      copy:
        src: ../../swarm_stacks/portainer_stack.yml
        dest: /tmp/portainer_stack.yml

    - name: Deploy portainer Icon app and tools from a stack file
      docker_stack:
        state: present
        name: portainer_stack 
        compose:
          - /tmp/portainer_stack.yml

    - name: delete stack file
      file:
        path: /tmp/portainer_stack.yml
        state: absent

