- hosts: docker_swarm_manager
  become: yes

  tasks:

    - name: copy monster app stack file to remote
      copy:
        src: ../../swarm_stacks/monster_icon_stack.yml
        dest: /tmp/monster_icon_stack.yml

    - name: Deploy Monster Icon app and tools from a stack file
      docker_stack:
        state: present
        name: monsterstack
        compose:
          - /tmp/monster_icon_stack.yml

    - name: delete stack file
      file:
        path: /tmp/monster_icon_stack.yml
        state: absent