- name: Setup a k8s cluster using ansible and kubeadm"
  hosts: kubernetes

  pre_tasks:
    - apt:
        name: python3-pip
        update_cache: yes

    - name: link python to python3 (2020 no python2)
      file:
        state: link
        src: /usr/bin/python3
        dest: /usr/bin/python

  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_apt_release_channel: stable
        
    - role: anmoel.kubernetes
      vars:
        kubernetes_cluster_name: "moncluster"
        kubernetes_master_version: '1.16.2'
        kubernetes_imageRepository: "hub.docker.com"
        kubernetes_pod_subnet: "10.244.0.0/16"
        kubernetes_service_subnet: "10.96.0.0/16"
        kubernetes_kubelet_extra_args: ""
        