version: '3'
services:
  monster_icon:
    image: tecpi/monster_icon:0.1
    # image: <votre_hub_login>/monster_icon:0.1 # ou tecpi pour récupérer la mienne
    ports:
      - "9090:9090"
      - "9191:9191"
    environment:
      - CONTEXT=PROD
    networks:
      - monster_network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - monster_network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

  redis:
    image: redis
    networks:
      - monster_network
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - monster_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 500M
      restart_policy:
        condition: on-failure

networks:
  monster_network:

volumes:
  redis_data: