version: '3'
services:

  monster:
    image: tecpi/monster_icon:0.1
    # ports:
    #   - "9090:9090"
    #   - "9191:9191"
    environment:
      - CONTEXT=PROD
      - VIRTUAL_HOST=monster.test # for the proxy to know on which domain to forward 
      - VIRTUAL_PORT=9090 # port of the app backend for the proxy to forward to
    networks:
      - nginx_proxy
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
    networks:
      - nginx_proxy
volumes:
  certs:
  vhost:
  html:
networks:
  nginx_proxy: