version: '3'
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    environment:
      - CONTEXT=PROD
    networks:
      - portainer_network
    volumes:
      - portainer_data:/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
      restart_policy:
        condition: on-failure

networks:
  portainer_network:

volumes:
  portainer_data: